import PDFDocument from "pdfkit";
import { createSupabaseAdmin } from "@/lib/supabase/server";
import type { ToolContext } from "./tools";

// Renders simple markdown (#/##/### headings, - bullets, **bold** stripped) into a PDF,
// uploads to the private `artifacts` bucket, records it, returns a signed URL.
export async function generatePdfReport(
  title: string,
  markdown: string,
  ctx: ToolContext
): Promise<{ id: string; filename: string; url: string }> {
  const buffer = await renderPdf(title, markdown);

  const admin = createSupabaseAdmin();
  const safeTitle = title.replace(/[^a-zA-Z0-9-_ ]/g, "").trim().replace(/\s+/g, "-").slice(0, 60) || "report";
  const filename = `${safeTitle}.pdf`;
  const storagePath = `${ctx.userId}/${ctx.chatId}/${Date.now()}-${filename}`;

  const { error: upErr } = await admin.storage
    .from("artifacts")
    .upload(storagePath, buffer, { contentType: "application/pdf" });
  if (upErr) throw new Error(`artifact upload failed: ${upErr.message}`);

  const { data: row, error: insErr } = await admin
    .from("artifacts")
    .insert({ user_id: ctx.userId, chat_id: ctx.chatId, filename, storage_path: storagePath })
    .select("id")
    .single();
  if (insErr) throw new Error(`artifact record failed: ${insErr.message}`);

  const { data: signed, error: signErr } = await admin.storage
    .from("artifacts")
    .createSignedUrl(storagePath, 60 * 60 * 24 * 7); // 7 days
  if (signErr || !signed) throw new Error(`artifact signing failed: ${signErr?.message}`);

  return { id: row.id, filename, url: signed.signedUrl };
}

function renderPdf(title: string, markdown: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 54, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.font("Helvetica-Bold").fontSize(22).text(title, { align: "left" });
    doc.moveDown(0.3);
    doc
      .font("Helvetica")
      .fontSize(9)
      .fillColor("#666666")
      .text(`Generated by MicroManus — ${new Date().toUTCString()}`);
    doc.moveDown(1);
    doc.fillColor("#111111");

    const inline = (s: string) => s.replace(/\*\*([^*]+)\*\*/g, "$1").replace(/\*([^*]+)\*/g, "$1").replace(/`([^`]+)`/g, "$1");

    for (const rawLine of markdown.split("\n")) {
      const line = rawLine.trimEnd();
      if (!line.trim()) {
        doc.moveDown(0.4);
        continue;
      }
      if (line.startsWith("### ")) {
        doc.moveDown(0.3).font("Helvetica-Bold").fontSize(12).text(inline(line.slice(4)));
        doc.font("Helvetica").fontSize(10.5);
      } else if (line.startsWith("## ")) {
        doc.moveDown(0.5).font("Helvetica-Bold").fontSize(14).text(inline(line.slice(3)));
        doc.font("Helvetica").fontSize(10.5);
      } else if (line.startsWith("# ")) {
        doc.moveDown(0.6).font("Helvetica-Bold").fontSize(17).text(inline(line.slice(2)));
        doc.font("Helvetica").fontSize(10.5);
      } else if (/^\s*[-*] /.test(line)) {
        doc.font("Helvetica").fontSize(10.5).text(`• ${inline(line.replace(/^\s*[-*] /, ""))}`, {
          indent: 14,
          lineGap: 2,
        });
      } else if (/^\s*\d+\. /.test(line)) {
        doc.font("Helvetica").fontSize(10.5).text(inline(line.trim()), { indent: 14, lineGap: 2 });
      } else {
        doc.font("Helvetica").fontSize(10.5).text(inline(line), { lineGap: 2 });
      }
    }
    doc.end();
  });
}
